# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quadratic.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fquadratic.proto\x12\tquadratic\"/\n\x0c\x43oefficients\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"\x1a\n\x08Solution\x12\x0e\n\x06result\x18\x01 \x01(\t2H\n\x0fQuadraticSolver\x12\x35\n\x05Solve\x12\x17.quadratic.Coefficients\x1a\x13.quadratic.Solutionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quadratic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COEFFICIENTS']._serialized_start=30
  _globals['_COEFFICIENTS']._serialized_end=77
  _globals['_SOLUTION']._serialized_start=79
  _globals['_SOLUTION']._serialized_end=105
  _globals['_QUADRATICSOLVER']._serialized_start=107
  _globals['_QUADRATICSOLVER']._serialized_end=179
# @@protoc_insertion_point(module_scope)
